name: 'cppcheck-annotation-action'
description: 'Github action, which allows you to annotate C/C++ code in a pull request with warnings, errors, etc. from cppcheck static analysis tool'
runs:
  using: 'docker'
  image: 'Dockerfile'